const mongoose = require ("mongoose");
const parcelSchema = new mongoose.Schema({
      client: {type: String},
      dh_id: {type: String},
      tracking_number: {type: String},
      order_no: {type: String},
      consignee_name: {type: String},
      consignee_mobile: {type: String},
      consignee_email: {type: String},
      consignee_address: {type: String},
      address_province: {type: String},
      address_city: {type: String},
      address_barangay: {type: String},
      payment_type: {type: String},
      length: {type: String},
      width: {type: String},
      height: {type: String},
      quantity: {type: String},
      weight: {type: String},
      volume: {type: String},
      package_size: {type: String},
      declared_value: {type: String},
      total_price: {type: String},
      description: {type: String},
      riderName01: {type: String},
      dispatched01: {type: String},
      status01: {type: String},
      riderName02: {type: String},
      dispatched02: {type: String},
      status02: {type: String},
      riderName03: {type: String},
      dispatched03: {type: String},
      status03: {type: String},
      isDelivered: {
            type: Boolean,
            default: false,
      }
})
module.exports = mongoose.model("Parcel", parcelSchema);